load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/math/docs/pure",
    ],
    index = "index.md",
    slug = "mathematics",
    visibility = ["//visibility:public"],
)
