load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "stride",
    srcs = [
        "spoofing.md",
        "tampering.md",
        "repudiation.md",
        "information-disclosure.md",
        "dos.md",
        "eop.md",
    ],
    index = "index.md",
    slug = "stride",
    visibility = ["//visibility:public"],
)
