load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "foundational.md",
        "//projects/cryptography/cryptography/symmetric/docs",
        "//projects/cryptography/cryptography/asymmetric/docs",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
