load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/cryptography/cryptography/symmetric/monoalphabetic/docs",
        "//projects/cryptography/cryptography/symmetric/polyalphabetic/docs",
        "//projects/cryptography/cryptography/symmetric/enigma/docs",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
