load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "identify",
    srcs = [
        "//projects/threat_modelling/docs/identify/stride",
        "eop.md",
        "brainstorming.md",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
