load("//rules:doc.bzl", "doc_publish")

doc_publish(
    name = "docs",
    srcs = [
        "//projects/translate/docs",
    ],
    index = "index.md",
    title = "Projects",
    visibility = ["//visibility:public"],
)
