load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "pure",
    srcs = [
        "sets.md",
        "functions.md",
        "logic.md",
        "//projects/math/docs/pure/proofs",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
