load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "shell",
    srcs = [
        "prompt.md",
    ],
    index = "index.md",
    slug = "shell",
    visibility = ["//visibility:public"],
)
