load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "linux",
    srcs = [
        "distros.md",
        "permissions.md",
        "//projects/linux/shell",
        "commands.md",
        # "filter.md",
        "descriptors.md",
        "ssh.md",
        "regex.md",
        "//projects/linux/vim",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
