load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "foundational.md",
        "//projects/threat_modelling/docs/model",
        "//projects/threat_modelling/docs/identify",
        "//projects/threat_modelling/docs/mitigate",
        "//projects/threat_modelling/docs/verify",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
