load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "approaches",
    srcs = [
        "assets.md",
        "attackers.md",
        "software.md",
    ],
    index = "index.md",
    slug = "structured-approaches",
    visibility = ["//visibility:public"],
)
