load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "rust",
    srcs = ["main.rs"],
    deps = [
        "@crates//:anyhow",
    ],
)