load("//rules:doc.bzl", "doc_section")


doc_section(
    name = "docs",
    srcs = [
        "index.md",
        "translate_srt.md"
    ],
    data = [
        "//projects/translate/docs/data"
    ],
    visibility = ["//visibility:public"],
)