load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    index = "index.md",
    srcs = [
        "docs.md",
    ],
    data = [
        "//projects/budget/docs/data",
    ],
    visibility = ["//visibility:public"],
)
