load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    name = "markdownlint_cli2",
    entry_point = "markdownlint_cli2.mjs",
    data = ["//toolchains/js:node_modules/markdownlint-cli2"],
)
