load("@rules_python//python:defs.bzl", "py_binary", "py_test")

py_binary(
    name = "python",
    srcs = [
        "main.py",
    ],
    main = "main.py",
)

py_test(
    name = "test",
    srcs = ["main.py"],
)