load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "bpf.md",
        "pdu.md",
        "security.md",
        "//projects/networking/docs/osi",
        "//projects/networking/docs/tcpip",
        "//projects/networking/gopher/docs",
        "//projects/networking/mqtt/docs",
        "//projects/networking/docs/analysis",
    ],
    index = "index.md",
    slug = "networking",
    visibility = ["//visibility:public"],
)
