load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    data = [
        "//projects/cryptography/cryptography/asymmetric/rsa/docs/data",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
