exports_files([
    "rules_hugo_module.patch",
    "rules_hugo_workspace.patch",
    "rules_hugo_repository.patch",
    "rules_hugo_site.patch",
    "com_github_alex_shpak_hugo_book.patch",
    "com_github_thegeeklab_hugo_geekdoc.patch",
])
