load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "verilog.md",
        "mux.md",
        "full-adder.md",
        "hazards.md",
        "overflow-counter.md",
        "clock-division.md",
        "seven-segment-display.md",
    ],
    data = [
        "//projects/fpga/docs/data",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
