load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "diagrams",
    srcs = [
        "dfd.md",
        "uml.md",
        "sl.md",
        "state.md",
        "tb.md",
    ],
    data = ["//projects/threat_modelling/docs/model/diagrams/data"],
    index = "index.md",
    visibility = ["//visibility:public"],
)
