load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "osi",
    srcs = [
        "physical.md",
        "link.md",
        "network.md",
        "transport.md",
        "session.md",
        "presentation.md",
        "application.md",
    ],
    index = "index.md",
    slug = "osi-network-model",
    visibility = ["//visibility:public"],
)
