load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "attack_trees",
    srcs = [
        "creating.md",
        "representing.md",
        "example.md",
        "irl.md",
        "limitations.md",
    ],
    data = ["//projects/threat_modelling/docs/identify/attack_trees/data"],
    index = "index.md",
    visibility = ["//visibility:public"],
)
