load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "proofs",
    srcs = [
        "even.md",
        "odd.md",
        "positive.md",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
