load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/networking/mqtt/stress_tester/docs",
    ],
    index = "index.md",
    slug = "mqtt",
    visibility = ["//visibility:public"],
)
