load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/cryptography/cryptography/asymmetric/rsa/docs",
        "//projects/cryptography/cryptography/asymmetric/ecc/docs",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
