load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/networking/gopher/crawler/docs",
    ],
    index = "index.md",
    slug = "gopher",
    visibility = ["//visibility:public"],
)
