load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "model",
    srcs = [
        "//projects/threat_modelling/docs/model/approaches",
        "//projects/threat_modelling/docs/model/diagrams",
    ],
    index = "index.md",
    slug = "model",
    visibility = ["//visibility:public"],
)
