load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "model",
    srcs = [],
    index = "index.md",
    data = ["//projects/threat_modelling/docs/model/data"],
    visibility = ["//visibility:public"],
)
