name: Premerge Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  Toolchains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Debug Compiler
        run: |
          set -euxo pipefail

          which clang || true
          which clang++ || true
          which gcc || true
          which g++ || true

          clang --version || true
          clang++ --version || true
          gcc --version || true

          echo | clang -E -x c - -v || true
          echo | clang++ -E -x c++ - -v || true

          clang -print-resource-dir || true

      - name: Run toolchain tests
        run: |
          set -euxo pipefail

          bazel test //projects/hello_world/...
          bazel test //toolchains/...